### ISSUE TITLE
Segmentation error using example file from BA3

### ISSUE THREAD

**Issue by patriciahimeka** [smussmann82/BayesAss3-SNPs#1]
Hi Steve,
Thanks for this contribution. 

I tried running BayesAss3-SNPs on the 2-populations example file from BA3 on a linux cluster using one cpu with 5G memory, but I get a segmentation error:

 ~/BayesAss3-SNPs-master/BA3-SNPS -F ~/BA3-3.0.4/examples/2pop.txt -l 9 

                    BayesAss Edition 3.0.4 (BA3)                    
                        Released: 09/28/2015                        
                            Bruce Rannala                           
           Department of Evolution and Ecology at UC Davis          

Made new Indiv object
Going to read input file
Setting alleles
Segmentation fault (core dumped)

What am I missing? 
Best,
Patricia

**Comment by smussmann82** [comment]
Good morning Patricia,

It looks like the 2pop.txt file contains 10 loci (the loci are numbered 0 through 9).  I received the same segmentation fault when using your command, but it worked when I changed it to: `BA3-SNPS -F ~/BA3-3.0.4/examples/2pop.txt -l 10`

Thank you for pointing this out - it's a good reminder that I need to update the code so it provides a useful error message rather than throwing a segfault.  If you run into any more issues just let me know.

-Steve

**Comment by patriciahimeka** [comment]
Hi Steve,
Thank you for your reply and apologies for this simple question, it works perfectly with -l 10.
I do have issues running it on my own file:

```
~/BayesAss3-SNPs-master/BA3-SNPS -F ./REDUCED2.2.txt -l 100


                    BayesAss Edition 3.0.4 (BA3)                    
                        Released: 09/28/2015                        
                            Bruce Rannala                           
           Department of Evolution and Ecology at UC Davis          


Made new Indiv object
Going to read input file
Setting alleles
Read input file
gsl: ../gsl/gsl_rng.h:200: ERROR: invalid n, either 0 or exceeds maximum value of generator
Default GSL error handler invoked.
Aborted (core dumped)
```

I converted my file from VCF using PGDSpider 2.1.1.3. There are 104 individuals in 8 populations and 100 loci (10400 lines). Here some example lines of `REDUCED2.2.txt`:

```
ChichiPW562comb  Chichi   SNP_1    130      130
ChichiPW568comb  Chichi   SNP_1    130      130
DaitoPW199       Daito    SNP_1    0        0
DaitoPW201       Daito    SNP_1    130      130
```
Have you come across this error before or have any suggestions what could be wrong about my input file? I'm happy to send you the file if it helps.

Many thanks,
Patricia

**Comment by smussmann82** [comment]
Hi Patricia,

That is a new problem I have not encountered before, and I'm not sure what is causing it.  Since the error looks to be coming from the GSL random number generator, my only immediate suggestion is to try providing a different random number seed using the -s option and see if that makes a difference.

I can't see anything wrong with the example lines from your input file that you have posted.  If you could send me the file (my email is mussmann@email.uark.edu) it would be of great help in debugging the problem.  Also, could you please tell me which GSL version you have, and the operating system you are using?  

I have to work at my job the rest of the week, so I may not have time to debug this until the weekend, but I'll try to take a look at it before then.

-Steve
